export const REFUSAL_REASONS = {
    // Protocol-level refusal reasons
    SCHEMA_MISMATCH: 'SCHEMA_MISMATCH',
    MISSING_EXPORT_SCHEMA_VERSION: 'MISSING_EXPORT_SCHEMA_VERSION',
    MISSING_INTEGRITY_HASH: 'missing_integrity_hash_for_branch_suffix',
    MISSING_PRODUCER_IDENTITY: 'MISSING_PRODUCER_IDENTITY',
    MISSING_REPOSITORY_HINT: 'MISSING_REPOSITORY_HINT',
    MALFORMED_REPOSITORY_HINT: 'MALFORMED_REPOSITORY_HINT',
    REPOSITORY_IDENTITY_MISMATCH: 'repository_identity_mismatch_with_runtime_context',

    // Provider-specific refusal reasons
    MISSING_GITHUB_TOKEN: 'MISSING_GITHUB_TOKEN',
    OCTOKIT_EXECUTION_FAILED: 'OCTOKIT_EXECUTION_FAILED',
    MISSING_GITLAB_TOKEN: 'MISSING_GITLAB_TOKEN',
    MISSING_FILE_ON_DISK: 'MISSING_FILE_ON_DISK',
    COMMIT_CREATION_FAILED: 'COMMIT_CREATION_FAILED',
    MERGE_REQUEST_CREATION_FAILED: 'MERGE_REQUEST_CREATION_FAILED'
} as const;

export type RefusalReason = typeof REFUSAL_REASONS[keyof typeof REFUSAL_REASONS] | string;
